[context.production.environment]
BACKEND_URL = "https://back.outdoorvision.fr/auth/"

[context.staging.environment]
BACKEND_URL = "https://staging-back.outdoorvision.fr/auth/"

[context.qa.environment]
BACKEND_URL = "https://qa-back.outdoorvision.fr/auth/"

[context.dev.environment]
BACKEND_URL = "https://staging-auth.outdoorvision.fr/auth/realms/PRNSN/protocol/openid-connect/registrations?client_id=back1-outdoorgeovision-prnsn&response_type=code&redirect_uri=https://dev-back.outdoorvision.fr/auth/done/&scope=openid"
